### ISSUE TITLE
Run test through proxy server

### ISSUE THREAD

**Issue by ALTELMA** [meare/codeception-mountebank#2]
I have problem to run codeception through proxy server.
I got error messages like this 
`DELETE http://mountebank:2525/imposters resulted in a 503 Service Unavailable`.

I am newbie for **mountebank**. Need someone can help to fix this problem.
Actually It works without proxy, but I need to work on proxy environment.

Please help me :)

**Comment by meare** [comment]
Hey!

You mean you set up WebDriver to work through proxy server? Could you please post your Codeception configuration?

**Comment by ALTELMA** [comment]
Yes, I try to do it, but I have no idea about proxy server. Here Codeception configuration.

```
# Codeception Test Suite Configuration
#
actor: AcceptanceTester
modules:
    enabled:
          - \Helper\Acceptance
          - WebDriver:
                host: chromedriver
                port: 4444
                url: %ASSETS_BASE_URI%
                browser: chrome
          - Mountebank:
                host: 'mountebank'
                port: 2525
                imposters:
                    sso:
                        contract: 'tests/_data/mountebank/sso/stub.json'
                        save: 'tests/_output/mountebank/sso/output.json'
                        mock: true
env:
    desktop:
        modules:
            config:
                WebDriver:
                    window_size: false
                    capabilities:
                        chromeOptions:
                            args: ["disable-infobars", "headless","disable-gpu", "window-size=1920x1080"]
    mobile:
        modules:
            config:
                WebDriver:
                    window_size: 360x640
                    capabilities:
                        chromeOptions:
                            mobileEmulation:
                                deviceName: 'Nexus 5'
extensions:
    enabled:
        - Codeception\Extension\RunProcess:
            - chromedriver
config:
    API_ROUTE: %API_ROUTE%
```
